### ISSUE TITLE
Plural form of a noun

### ISSUE THREAD

**Issue by kulikalov** [nextapps-de/flexsearch#185]
```
FlexSearch.create()
index.add(123, 'Strawberries, packed, frozen')
index.add(234, 'Strawberry')
...
index.search('Strawberry frozen')
```
Depending on configs, search results are either empty or 99% filled with absolutely irrelevant results.

I've tried all recommended presets, a bunch of variations of the `create` options, [custom stemmer](https://www.npmjs.com/package/en-stemmer) etc. 

This seems like a very basic thing. What am I doing wrong? Why doesn't it work out of the box?

**Comment by kulikalov** [comment]
hello?

**Comment by kulikalov** [comment]
using this for now:

```
import Snowball from 'snowball'

var stemmer = new Snowball('English')

const index = FlexSearch.create({
  encode: sentence => {
    const wordsArr = sentence.split(' ').map(word => {
      const cleanWord = word.replace(/[^a-zA-Z ]/g, '')
      stemmer.setCurrent(cleanWord)
      stemmer.stem()
      return stemmer.getCurrent()
    })
    return wordsArr.join(' ').toLowerCase()
  },
  tokenize: 'forward'
})
```

**Comment by weishuhn** [comment]
I didn't test your code in previous versions of flexsearch so I don't know if it was working before, but in the latest version (0.7+) I had to change `return wordsArr.join(' ').toLowerCase()` to just `return wordsArr;` because it's expecting an array as the return value.  Before I caught that I was having the same problem you were having above where it was returning totally irrelevant results.

**Comment by ts-thomas** [comment]
Using "stemmer" is the right answer. Also the "encode" method needs to return an array of words/terms.
