### ISSUE TITLE
How to use it on typescript ?

### ISSUE THREAD

**Issue by avelinocneto** [nextapps-de/flexsearch#196]
Please can you explain how to use with Typescript and NodeJS ?

**Comment by ishanuda** [comment]
Hi,

Please follow the documentation and get an idea.

[Documentation 0.7.0-rev2](https://github.com/nextapps-de/flexsearch/blob/0.7.0/doc/0.7.0.md)

Regards

**Comment by hinell** [comment]
The best solution is probably to fallback to `/// <reference types="..." />` or specify types path in the `tsconfig.json`

**Comment by hinell** [comment]
The best solution is probably to fallback to `/// <reference types="..." />` or specify [types] path in the `tsconfig.json`

[types]: ../blob/master/index.d.ts

**Comment by Rebolon** [comment]
Just a little update: i'm using Angular 11 which is delivered with:
* "@types/node": "^12.11.1"
* "typescript": "~4.0.2"

Here is my tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```

In fact in my IDE, the require is always underlined in red: TS2591 cannot find name 'require'...
And when the application run, it fails because flexsearch is undefined and so i cannot call create function.
Any clue ? 
I've tried this in tsconfig.json but still a failure : "esModuleInterop": true

```
const flexsearch = require('flexsearch');

@Injectable()
export class Cites {
  // didn't find a way to specify type Index ?
  protected index;
  public constructor() {
    const index = flexsearch.create({
      // mandatory:
      encode: (str) => str,
      // optionally:
      rtl: false,
      stemmer: {},
      // matcher: {},
      filter: false,
      tokenize: 'strict',
      depth: 3,
      doc: {
        id: 'id',
        field: ['cite', 'author']
      }
    });
  }
```

Thanks for help,
