### ISSUE TITLE
Uncaught TypeError: this.encode is not a function

### ISSUE THREAD

**Issue by Christilut** [nextapps-de/flexsearch#201]
```
flexsearch.js:1 Uncaught TypeError: this.encode is not a function
    at FlexSearch../node_modules/flexsearch/dist/module/flexsearch.js.FlexSearch.add (flexsearch.js:1)
    at flexsearch.js:1
```

I'm getting the above error when adding an encode: `encode: 'simple'` or any other.

Full code:
```
import FlexSearch from 'flexsearch/dist/module/flexsearch'

const index = new FlexSearch({
          tokenize: 'forward', // Allows partial results
          encode: 'simple',
          async: true,
          limit: 100,
          depth: 1,
          bool: 'or',
          doc: {
              id: '_id',
              field: ['foo', 'bar']
          }
        })

index.add([array of items])

await index.search('test')
```

**Comment by marxys** [comment]
Hello, I faced the same issue. I think the doc is not up to date about that. A function is expected for the property "encode". 
 So Flexsearch try to call a string as a function.
 
 If you want to use encode you have to use property charset with the value '[your charset]:[encode name]' (ex: 'latin:simple'). instead of using the property encode.

**Comment by ts-thomas** [comment]
Question answered.

**Comment by ShivamJoker** [comment]
Shouldn't this be updated in the docs?
