### ISSUE TITLE
Forward, only for last search token; if not ended by whitespace

### ISSUE THREAD

**Issue by patarapolw** [nextapps-de/flexsearch#217]
## Forward-only for last search segment 

For example, `eye ca` shouldn't return `eyeball cats`; however, it can return `eye cats`

## Forced full words

For example, `eye ca   ` mustn't return `eye cats`; only `eye CA cat`

**Comment by ts-thomas** [comment]
That's a good point. I would not say "eye ca" shouldn't never return "eyeball cats" when forward tokenizer was used. But I absolutely confirm that the result "eye cats" should be higher ranked in the result. When we strictly just apply forward tokenizer for the last word, you will loose some matches (e.g. singular vs. plural when you type "eye" but the full word is "eyes"). Sadly the design of the index does not profit when just applying the forward tokenizer on the last word, it still needs every word to be indexed as forward incremental partials. That would be a great deal otherwise. So what's left is just the order in the result-set which should be higher ranked on non-partial matches.
