### ISSUE TITLE
Question about query with multiple words in multiple fields

### ISSUE THREAD

**Issue by FrancescoBonizzi** [nextapps-de/flexsearch#314]
Consider this index definition: 

```
const databaseIndex = new Document({
    preset: 'match',
    tokenize: 'full',
    language: 'it',
    resolution: 1,
    charset: 'latin:advanced',
    document: {
        id: 'id',
        index: ['id', 'brand', 'name'],
    },
});
```

I add the items to the document like this:
```
rawProductsList.forEach((element) => {
    databaseIndex.add(element);
});
```

Consider a simple set of objects like this:
| id | brand   | name    |   |   |
|----|---------|---------|---|---|
| 0  | oreo    | biscuit |   |   |
| 1  | barilla | biscuit |   |   |
|    |         |         |   |   |

When i search for 'oreo' or 'biscuit' I get the correct results, but what I want to achieve is that a query `oreo biscuit` gives me the object with id 1, but in my configuration it doesn't return anything. 

How can I do it?
Thanks.

**Comment by ts-thomas** [comment]
You will need to apply logical operator manually to the result (like union):

```js
const index = new Document({
    preset: 'match',
    tokenize: 'full',
    language: 'it',
    resolution: 1,
    charset: 'latin:advanced',
    document: {
        id: 'id',
        index: ['id', 'brand', 'name'],
    },
});

index.add({ id: 0, brand: "oreo", name: 'biscuit' });
index.add({ id: 1, brand: "barilla", name: 'biscuit' });

const result = index.search([{
    field: "brand",
    query: "oreo"
},{
    field: "name",
    query: "biscuit"
}]);

const union = [...new Set(...result.map(res => res.result))];

console.log(union);
```

**Comment by drzraf** [comment]
While I understand the reason to leave this to the implementer, there are also strong ones to implement it internally:
- To do it right once for all
- To do it efficiently
- Because the given example assume only two fields but there may be more
- To avoid the limitations caused by `limit` (and the performance costs it'd incurs to artificially increase it).

Searching for results having two or more terms **across** all distinct Document fields is a must-have and should be possible without having to ressort to individual inefficient OR-ed queries.
