### ISSUE TITLE
[Question] Is this project dead? Call for maintainers?

### ISSUE THREAD

**Issue by brendanmoore** [nextapps-de/flexsearch#336]
Hi there 

Firstly I'd like to say I think this project is great I really love its features and the effort that has gone into making it. I have noticed a few bugs here and there and a few errors in the documentation and types and I am keen to help out. I see that it has been a long time since the code has been worked on... Does that mean the project no longer maintained? If so would you be open to allowing new maintainers into the project?

Thanks

**Comment by ts-thomas** [comment]
In the past I didn't make any good experience with maintainers, because often they doesn't fully understand the concept. Most of pull requests have introduced new side-effects I need to fix additionally. Actually there is planning of funding this project. This is best option to regularly provide updates.
