### ISSUE TITLE
Offset support for implementing pagination 

### ISSUE THREAD

**Issue by georgyfarniev** [nextapps-de/flexsearch#34]
Hello. Is there any plans to support offset in addition to limit for implementing pagination? Thanks in advance.

**Comment by ts-thomas** [comment]
Hello. Technically a pagination would not cut any (or too less) complexity of the algorithm, that's why is actually not supported. Since documents are supported it may be good to reduce response size from results by traversing trough the results via a pagination pointer. The implementation is basically done in the other project "BulkSearch" so I can simply reuse it. Will be available soon.

**Comment by georgyfarniev** [comment]
@ts-thomas at least it useful for consistent interface and to prevent redundant data transfer. Thank you very much for your response and rapidly improving this useful engine.

**Comment by ts-thomas** [comment]
Just released in v0.6.0
