### ISSUE TITLE
.export(..) returns bool sync but internally runs async...

### ISSUE THREAD

**Issue by flynx** [nextapps-de/flexsearch#353]
Hi,

It seems that `.export(..)`, at least on the `Index`, returns true right away but internally runs asynchronously, this is a big issue if one is trying to partition or join the exported data in a custom way, for example it is not possible to collect all the exported data into one object and do something with it...

A basic example:
```javascript
console.log(pre)
console.log(
    index.export(function(key, value){
        console.log('export')
    }) )
console.log('post')
```
This prints out:
```
pre
true
post
export
...
export
```

It would be nice/logical to be able to `await` for the export to be done, i.e. for `.export(..)` to return a promise.

Would also be nice if this promise would account for the handler returning a promise, i.e. resolve when all the returned values are resolved (i.e. via `Promise.all(..)`)

Thanks!

**Comment by TixieBorg** [comment]
+1, the documentation says import/export functions are async but we can't actually use it in an async context because it's impossible to know when the operations are done. Quite frustrating

![Screenshot 2023-01-28 at 23 42 17](https://user-images.githubusercontent.com/2143796/215295880-d05f4b18-e10a-41c1-9c17-e7a6f35e0456.png)

**Comment by thexeos** [comment]
The above PR allows for `await` on export method, which resolves immediately after the last call to `callback` was made.
