### ISSUE TITLE
Remove Features: Where / Find / Tags

### ISSUE THREAD

**Issue by ts-thomas** [nextapps-de/flexsearch#37]
I thinking about to remove these features:

- `index.find()` (get document by ID will remain)
- `index.where()`
- tag fields
- where clause in custom search

The main reasons for this may:

- they do not scale properly, just useful up to a medium size of document length
- tags cannot be serialized, instead they need to recover from the original documents which slows down the import function
- a custom helper function will replace this functionality and is also faster and also less redundant

What do you think about?

**Comment by georgyfarniev** [comment]
I think it probably makes sense to have only one method that performs search operation itself, with different set of parameters and overloads. Typescript definitions could be handy for this purpose, as they will simplify using of **flexsearch**.

Talking about **where** method, it's always useful and less redundant to write query as JS object, in similar way to **mongodb** API, but I think this option should be provided by **search** method interface. Only question here is compatibility.

As you are well familiar with this search engine implementation and underlying algorithms, I suggest to create proposal document with case-study of most typical tasks that usually needed for search, and you will give estimation of complexity and probability to implement these tasks. I bet if we give enough attention for these problems, your project will be very successful, because world really lacks such lightweight and efficient alternative to humongous **elasticsearch**, **solr** or really old and also sophisticated **sphinx**.

Currently, we are working on ecommerce platform and we can provide real-world needs information to you, along with future partnership when we launch.

Could you please provide your private contact details, so we can show you our current development version of product?

**Comment by ts-thomas** [comment]
Thanks for your reply. I am currently researching what the key points are. I also made a list of features which may be interest:

https://github.com/nextapps-de/flexsearch/milestones
https://github.com/nextapps-de/flexsearch-server/milestones

My team also think about to make a service available to provide as a SaaS out-of-the-box.
