### ISSUE TITLE
I have a question about how the results are sorted

### ISSUE THREAD

**Issue by mtrucc** [nextapps-de/flexsearch#431]
```
const { Index } = require("flexsearch");

const data1 = [
  "你家里生的和你用银子买的，都必须受割礼。这样，我的约就立在你们肉体上作永远的约。", // 0
  "你若不肯容他们去，我必使青蛙糟蹋你的四境。", // 1
  "你们要吃无酵饼七日。头一日要把酵从你们各家中除去；因为从头一日起，到第七日为止，凡吃有酵之饼的，必从以色列中剪除。", // 2
  "你要在山的四围给百姓定界限，说：‘你们当谨慎，不可上山去，也不可摸山的边界；凡摸这山的，必要治死他。", // 3
  "你们要侍奉耶和华你们的　神，他必赐福与你的粮与你的水，也必从你们中间除去疾病。", // 4
  "你要对他们说：你们世世代代的后裔，凡身上有污秽、亲近以色列人所分别为圣、归耶和华圣物的，那人必在我面前剪除。我是耶和华。", // 5
  "你们要追赶仇敌，他们必倒在你们刀下。", // 6
  "你们五个人要追赶一百人，一百人要追赶一万人；仇敌必倒在你们刀下。", // 7
  "你们剩下的人必因自己的罪孽和祖宗的罪孽在仇敌之地消灭。", // 8
  "你若和我们同去，将来耶和华有什么好处待我们，我们也必以什么好处待你。”", // 9
  "你们要在这日守为圣安息日，世世代代作为永远的定例。", // 10
  "你们必晓得真理，真理必叫你们得以自由。”", // 11
];

var index = new Index({
  encode: (str) => str.split(""),
});

for (let i = 0; i < data1.length; i++) {
  index.add(i, data1[i]);
}

console.log(`你`, index.search("你", { suggest: true }));
console.log(`你们`, index.search("你们", { suggest: true }));
console.log(`你们必`, index.search("你们必", { suggest: true }));
console.log(`你们必`, index.search("你们必晓得", { suggest: true }));
```

return

```
你 [0, 1, 2, 3, 4, 5,  6, 7, 8, 9, 10, 11]
你们 [ 0,  1, 2, 3, 4, 5,  6, 7, 8, 9, 10, 11]
你们必 [ 0,  1, 2, 3, 4, 5,  6, 7, 8, 9, 11, 10]
你们必晓得 [ 11,  0, 1, 2, 3, 4,  5, 6, 7, 8, 9, 10]
```

But the result I expect is

```
你 [0, 1, 2, 3, 4, 5,  6, 7, 8, 9, 10, 11]
你们 [ 2, 4, 6, 7, 8, 9, 10, 11, 0, 1, 3, 5]
你们必 [ 11, 2, 4, 6, 7, 8, 9, 10, 0, 1, 3, 5]
你们必晓得 [ 11, 2, 4, 6, 7, 8, 9, 10, 0, 1, 3, 5]
```

I think when searching  `你们必`

```
"你们必晓得真理，真理必叫你们得以自由。”", // 11`
```

should be first

what should I do?

**Comment by DevBrent** [comment]
I'm new to this library but I believe your issue is the index encoding method of split("").

Once you index based on characters, you're doing a pure character-by-character search. Meaning we match the first character to any strings, then count that as a "hit" for that string, search the second character of your search string, and count those as a hit. Otherwise, you're getting the results back in the same as they are indexed.

This means document 0 ranks equal with document 11 because they both have all three input search characters.

I think this library just isn't well suited for logographic languages where positional proximity between words is vital.

In this same sense, you could recreate bad results with the following:


Red basket ball
Red hued cover on a purple ball
Purple basket and a red ball
Purple basket

Search: "Red ball"

Results: [ 0, 1, 2 ]
Ideal Results: [ 2, 0, 1 ] // Because the exact phrase is found in the third entry while the second and first entries only have both words.

**Comment by mtrucc** [comment]
> I'm new to this library but I believe your issue is the index encoding method of split("").
> 
> Once you index based on characters, you're doing a pure character-by-character search. Meaning we match the first character to any strings, then count that as a "hit" for that string, search the second character of your search string, and count those as a hit. Otherwise, you're getting the results back in the same as they are indexed.
> 
> This means document 0 ranks equal with document 11 because they both have all three input search characters.
> 
> I think this library just isn't well suited for logographic languages where positional proximity between words is vital.
> 
> In this same sense, you could recreate bad results with the following:
> 
> ```
> Red basket ball // 0
> Red hued cover on a purple ball // 1
> Purple basket and a red ball // 2
> Purple basket // 3
> Red ball with red stripes and extra ball // 4
> ```
> 
> Search: "Red ball"
> 
> Results: [ 0, 1, 2, 4 ] Ideal Results: [ 4, 2, 0, 1, 4 ]
> 
> Because the exact phrase is found in the third and fifth entry, they "should" come first. The fifth entry wins it on keyword density in an ideal search. The second and first entries only have both words but theoretically the first entry is more relevant to this topic phrase-wise.
> 
> I don't think this text search engine scores phrases, at least in your configuration.
> 
> Maybe use "Contextual Search" it offers?

Thank you very much for your reply. I understood the reason and tried Contextual Search. Although the results still did not achieve the expected results, this library is enough for me at the moment.
