### ISSUE TITLE
Cyrillic languages support

### ISSUE THREAD

**Issue by mahnunchik** [nextapps-de/flexsearch#51]
Hello,

I've faced with the following behaviour.

This example works as expected:
```js
const FlexSearch = require('flexsearch');
const index = new FlexSearch();

index.add(1, 'Foobar')
console.log(index.search('Foobar'));
// [ 1 ]
```

But this one shows no results.
```js
const FlexSearch = require('flexsearch');
const index = new FlexSearch();

index.add(1, 'Фообар')
console.log(index.search('Фообар'));
// []
```

I've tested in node and in browser.

**Comment by ts-thomas** [comment]
Hello. Try this settings: https://github.com/nextapps-de/flexsearch#cjk-word-break-chinese-japanese-korean

```js
var index = FlexSearch.create({
    encode: false,
    tokenize: function(str){
        return str.replace(/[\x00-\x7F]/g, "").split("");
    }
});
```
```js
index.add(1, "Фообар");
```
```js
var results = index.search("Фообар");
```

**Comment by mahnunchik** [comment]
Hello @ts-thomas 

Yep, it works with the following options.
```js
const index = new FlexSearch({
  tokenize: function(str){
    return str.replace(/[\x00-\x7F]/g, "").split("");
  }
});
```

But why it doesn't work with the `forward ` tokenizer?

**Comment by mahnunchik** [comment]
This one works too:

```js
const index = new FlexSearch({
  tokenize: function(str){
    return str.split("");
  }
});
```

**Comment by ts-thomas** [comment]
The forward tokenizer splits words via regex, but this regex will also remove cyrillic chars actually. The tokenizer needs to be enhanced to use „forward“ with non-latin content.

**Comment by mahnunchik** [comment]
It would be really helpful 😉

**Comment by ts-thomas** [comment]
@mahnunchik The latest version v0.6.1 has the new option __split__ when creating an index. This makes it possible to use built-in tokenizer like "strict" or "forward" (which is also required by the contextual index) and also handle word splitting separate.

```js
var index = FlexSearch.create({
    encode: false,
    split: /\s+/,
    tokenize: "reverse"
});
```
```js
index.add(0, "Фообар");
```
```js
var results = index.search("Фообар");
```
```js
var results = index.search("бар");
```
```js
var results = index.search("Фоо");
```

**Comment by mahnunchik** [comment]
@ts-thomas thank you! It helps me in my task.

Maybe there is sense to use more common `split` by default? To cover all languages which use space as separator of words.

It will be hard to find root of the problem for string like `foobar αβγ` with default split option `/\W+/`.

**Comment by ts-thomas** [comment]
The next main release will get an improvement of handling all language-specific features. This improvement will also cover splitting words.

**Comment by tareefdev** [comment]
The mentioned solutions here helped me to make FlexSearch indexing Arabic text. Thanks guys.

**Comment by ts-thomas** [comment]
Also take into account to use the "rtl" option for right-to-left support:

```js
var index = FlexSearch.create({
    encode: false,
    rtl: true,
    split: /\s+/,
    tokenize: "forward"
});
```

**Comment by Odrin** [comment]
@ts-thomas Is it possible to index mixed text content (cyrillic + latin)? Your approach doesn't work with it.

**Comment by gmfmi** [comment]
Hi @ts-thomas, last year you said:

> The next main release will get an improvement of handling all language-specific features.

As FlexSearch is currently in 0.7.0 release candidate, I was wondering if there is some new feature about languages processing.

I recently created a project called [SearchinGhost](https://github.com/gmfmi/searchinGhost#readme), it is an in-browser search plugins for Ghost CMS powered by FlexSearch. I am really happy with FlexSearch (thank your for the work done!) but I would like to bring multi-lang capabilities. For now, with what I read in the issues, I came up with these language default options:

Latin:
```js
FlexSearch.create({
    encode: "simple",
    tokenize: "forward"
});
```

Arabic
```js
FlexSearch.create({
    encode: false,
    rtl: true,
    split: /\s+/,
    tokenize: "forward"
});
```

Cyrilic, indian (any word separated by space language)
```js
FlexSearch.create({
    encode: false,
    split: /\s+/,
    tokenize: "forward"
});
```

Chinese, Japanese or Korean (with dedicated chars w/o spaces)
```js
FlexSearch.create({
    encode: false,
    tokenize: function(str){
        return str.replace(/[\x00-\x7F]/g, "").split("");
    }
});
```

Do you think there is any possible improvement/optimisation?

**Comment by EvanPartidas** [comment]
For some reason, the solution to this in typescript seems to be different. I'm just posting how I've gotten it to work in hopes it will help others. 

Note: I'm using `"flexsearch": "0.7.11"` because without that I was facing [this issue](https://www.reddit.com/r/typescript/comments/xuxcwk/getting_index_only_refers_to_a_type_but_is_being/) while using typescript.

I was not able to follow the `FlexSearch.create(< options >)` nor the `new FlexSearch(< options >)` paradigms I saw other's using here due to compile errors. The `split` field doesn't exist on the `new Index(< options >)`'s options type so that also caused compile errors. I tried to specify the charset as "cyrillic" and "cyrillic:default" but that also wasn't working.

I found that specifying the `encode` to a function of your choice is all you need to do.

It seems that the only function that actually matters is the encode function. I looked at the source and I played a bit and it seemed that when you specify an encoder, the tokenize, stemmer, and charset it doesn't affect anything.

Here's my working code:

```
import { Index } from "flexsearch";
import { PorterStemmerRu, WordTokenizer } from "natural";

const tokenizer = new WordTokenizer();

const index_ru = new Index({
    encode: (str) => {
        let ret = tokenizer.tokenize(str);
        for (let i = 0; i < ret.length; i++) {
            ret[i] = PorterStemmerRu.stem(ret[i]);
        }
        return ret;
    },
});
```

I'm using the [natural library](https://naturalnode.github.io/natural/) to handle the stemming.

I'm new to this library so please correct any horrible mistakes I've made!
