### ISSUE TITLE
What are "depth" and "threshold"?

### ISSUE THREAD

**Issue by TehShrike** [nextapps-de/flexsearch#53]
I don't know enough fulltext index terminology to infer what these two settings actually mean.

I'm guessing from context that "depth" is the maximum number of words/tokens away a term can be and still be considered relevant.

I have no idea what the "threshold" number implies. :-x

I know I want that sweet contextual searching, so I'd love to figure this out so I can pick numbers appropriate to my use case.

**Comment by TehShrike** [comment]
That image about contextual searching seems to confirm my understanding of "depth" – but I still can't figure this out:

> threshold of minimum relevance all results should have

**Comment by TehShrike** [comment]
ooh I have another one – what is "scoring resolution"?

**Comment by ts-thomas** [comment]
Hello. The depth is exactly what you said. Whereas __depth is the minimum relevance for the context-based index__, __threshold is the minimum relevance for the lexical index__. Threshold is an enhanced variation of a conventional scoring calculation, it uses document distance and partial distance instead of TF-IDF. The final scoring value is based on 3 kinds of distance (https://github.com/nextapps-de/flexsearch#model-of-context-based-scoring).

Resolution on the other hand specify the max scoring value. The final score value is an integer value, so resolution affect how many segments the score may have. When the resolution is 1, then there exist just one scoring level for all matched terms. To get more differentiated results you need to raise the resolution.

> The difference of both (_resolution_ - _threshold_) affects the performance on higher values.

The combination of resolution and threshold gives you a good controlling of your matches as well as performance, e.g. when the resolution is 25 and the threshold is 22, then the results only contains matches which are super relevant. The goal should be just have items in result which are really needed. On top, that also improves performance a lot.
