### ISSUE TITLE
function type stemmer is not supported

### ISSUE THREAD

**Issue by klyusba** [nextapps-de/flexsearch#59]
Only object type stemmer is supported

**Comment by ts-thomas** [comment]
Yes that's right. When you need customization through a function please use a <a href="https://github.com/nextapps-de/flexsearch#add-custom-encoder">custom encoder function</a> and apply stemmer logic there. The fields ___stemmer___ and ___filter___ will remain as declarative style, because that's the only advantage of this fields. Additionally it is planned to merge/aggregate those regex into one to improve performance, a declarative structure is required to make this possible.
