### ISSUE TITLE
Index Complex Document More Example Needed

### ISSUE THREAD

**Issue by mhmttosun** [nextapps-de/flexsearch#84]
Hi
I can't figure out how to index bolded field in this complex document. If you have to time to look, I appreciate. 

[data.docx](https://github.com/nextapps-de/flexsearch/files/3126234/data.docx)

var doc = [{ 
     id: 14,
     name: "xxxxx",
     code: "0001",
        term: 1,
        term_id: 1,
        Programs: {
            program_name: "Surgery",
            Program_Kind: {
                name: "Precourse",
                short_name: "OL"
            },
            Course_Kind: {
                short_name: "Distance Edu",
                abrv: "UE"
            }
        },
        Course_Instructor: [
            {
                id: 13,
                Instructors: {
                    f_name: "Me",
                    l_name: "Me",
                    Title: {
                        name: "Prof. Dr."
                    }
                }
            },
            {
                id: 14,
                Instructors: {
                    f_name: "xys",
                    l_name: "uipk",
                    Title: {
                        name: "Prof. Dr."
                    }

                }
            }
        ]
    }
];

#36

**Comment by Vokinloksar** [comment]
@mhmttosun I think it's better to format your code for better readability.

I got the same issue considering `documentation` for _field search_ as well. It took me about 2 hours to understand how to search through a simple Array:Object data structure, I think maybe it's better to link `field search` directly under `Search items` part, so that I don't have to check the whole doc to find it. like this:

## Search items

>   Index.search(string | options, <limit>, <callback>)

```
index.search("John");
```

See also [Field Search](#field-search)

**Comment by ts-thomas** [comment]
@Vokinloksar  That's a good point, thanks.
